on:
  workflow_call:
    inputs:
      network:
        required: true
        type: string
      test:
        required: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NETWORK: ${{ inputs.network }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '16.17.0'
      - run: yarn install
      - run: quasar build
  test:
      name: test
      runs-on: ubuntu-latest
      needs:
        - build
      if: inputs.test
      steps:
        - run: yarn test
        - run: yarn lint

        - name: Passed ✅
          if: ${{ success() }}
          run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "tests",
              "state": "success",
              "description": "passed ✅",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }'

        - name: Failed 🚨
          if: ${{ failure() }}
          run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "tests",
              "state": "failure",
              "description": "failed 🚨",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }'

