on:
  push:
    branches:
      - master
      - dev
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  mainnet:
    runs-on: ubuntu-latest
    needs:
      - checkout
    steps:
    - uses: ./.github/workflows/build_job.yml
      with:
        network: mainnet
        test: false
    - uses: ./.github/workflows/publish_job.yml
      with:
        account_id: 0dd44352714dc8c855d81b72164cd961
        branch: ${{ GITHUB_REF##*/ == 'master' && 'production' || GITHUB_REF##*/ }}
        project: deployment-testing-mainnet
  testnet:
    runs-on: ubuntu-latest
    needs:
      - checkout
    steps:
      - uses: ./.github/workflows/build_job.yml
        with:
          network: testnet
          test: false
      - uses: ./.github/workflows/publish_job.yml
        with:
          account_id: 0dd44352714dc8c855d81b72164cd961
          branch: ${GITHUB_REF##*/}
          project: deployment-testing-testnet
